apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustyweb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rustyweb/overlays/production
    repoURL: https://github.com/netguy204/prototype-git-ops
  syncPolicy:
    automated: {}
    syncOptions:
    - PruneLast=true
