apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustyweb
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: REVISION
          value: 1ef0eb4c75cb650f1019e1cd88ea798b593190ae
