apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: rustyweb
spec:
  additionalTags:
  - us-east1-docker.pkg.dev/prod-prototype/default/rustyweb:985ff9fac3b9a6ad2ba4641b5b2fe801efee3961
  source:
    git:
      revision: 985ff9fac3b9a6ad2ba4641b5b2fe801efee3961
