apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patchesStrategicMerge:
- image-patch.yaml
- deploy-patch.yaml

images:
- name: us-east1-docker.pkg.dev/prod-prototype/default/rustyweb
  newTag: 76bc632928112df8efdc6dca4c2b01c938046127
