apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: artifact-key
metadata:
  name: kpack-builder
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: kpack-builder@prod-prototype.iam.gserviceaccount.com
secrets:
- name: artifact-key