apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: rustyweb
  namespace: default
  metadata:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: rustyweb
spec:
  tag: us-east1-docker.pkg.dev/prod-prototype/default/rustyweb
  builder:
    name: rust-builder
    kind: Builder
  serviceAccountName: kpack-builder
  build:
    env: []
    resources:
      requests:
        ephemeral-storage: 4G
        cpu: 2
      limits:
        ephemeral-storage: 4G
        cpu: 2
  source:
    git:
      url: https://github.com/netguy204/rustyweb
      revision: version