apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: nodularweb
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: REVISION
          value: __REVISION__
  additionalTags:
  - us-east1-docker.pkg.dev/prod-prototype/default/nodularweb:__REVISION__
  source:
    git:
      revision: __REVISION__
