apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: nodularweb
spec:
  additionalTags:
  - us-east1-docker.pkg.dev/prod-prototype/default/nodularweb:8d8ecce5c34fca6ddb544d7d4c2fae2f0723c7da
  source:
    git:
      revision: 8d8ecce5c34fca6ddb544d7d4c2fae2f0723c7da
