apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __NAME__
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: __NAME__/overlays/production
    repoURL: https://github.com/netguy204/prototype-git-ops
    targetRevision: __NAME___production_released_to_deploy
  syncPolicy:
    automated: {}
    syncOptions:
    - PruneLast=true
